### ISSUE TITLE
Dynamic Node Height Adjustment

### ISSUE THREAD

**Issue by jimmm-ai** [jimmm-ai/TimeUi-a-ComfyUi-Timeline-Node#3]
Implement a solution for dynamically adjusting the node's height based on the content to prevent overflow issues.

<img width="721" alt="Capture d’écran 2024-06-07 à 18 18 17" src="https://github.com/jimmm-ai/TimeUi-a-ComfyUi-Timeline-Node/assets/171628007/2b07843e-7048-4cca-872e-077f62ba7eb8">

**Comment by corbin-hayden13** [comment]
Feature implemented
